### ISSUE TITLE
Invalid TAP string, number of tests does not match specified test count.

### ISSUE THREAD

**Issue by tobiastom** [Block8/PHPCI#571]
I've added this login section to the `phpunit.xml` file:

```
<logging>
    <log type="coverage-html" target="Build/Coverage/" charset="UTF-8" highlight="false" lowUpperBound="35" highLowerBound="70"/>
    <log type="coverage-clover" target="Build/Coverage/index.xml"/>
    <log type="coverage-text" target="Build/Coverage/index.txt" showUncoveredFiles="false"/>
    <log type="tap" target="Build/Coverage/index.tap"/>
</logging>
```

The result seems to be:

```
TAP version 13
ok 1 - …
ok 2 - …
…
ok 45 - …
ok 46 - …
1..46
Generating code coverage report in Clover XML format ... done
Generating code coverage report in HTML format ... done
```

The error I get is this:

```
EXCEPTION: Invalid TAP string, number of tests does not match specified test count.
PLUGIN STATUS: FAILED
```

**Comment by Caffe1neAdd1ct** [comment]
Hi Guys,

Just started using PHPCI, absolutly brilliant project! Had this up and running on my local machine in under 5 mintues :+1: 

Just came across this issue:

```
RUNNING PLUGIN: php_unit
TAP version 13
TAP version 13
ok 1 - Billing_Model_CountryServiceTest::testThisFunctiRUNNING PLUGIN: php_unit
TAP version 13
TAP version 13
ok 1 - Billing_Model_CountryServiceTest::testThisFunction
ok 1 - Billing_Model_CountryServiceTest::testThisFunction
ok 2 - Billing_Model_CountryTest::testGetId
ok 2 - Billing_Model_CountryTest::testGetId
ok 3 - Billing_Model_CountryTest::testGetName
ok 3 - Billing_Model_CountryTest::testGetName
ok 4 - Billing_Model_CountryTest::testGetCode
ok 4 - Billing_Model_CountryTest::testGetCode
ok 5 - Billing_Model_CountryTest::testGetVatChargableFlag
ok 5 - Billing_Model_CountryTest::testGetVatChargableFlagon
ok 1 - Billing_Model_CountryServiceTest::testThisFunction
ok 2 - Billing_Model_CountryTest::testGetId
ok 2 - Billing_Model_CountryTest::testGetId
ok 3 - Billing_Model_CountryTest::testGetName
ok 3 - Billing_Model_CountryTest::testGetName
ok 4 - Billing_Model_CountryTest::testGetCode
ok 4 - Billing_Model_CountryTest::testGetCode
ok 5 - Billing_Model_CountryTest::testGetVatChargableFlag
ok 5 - Billing_Model_CountryTest::testGetVatChargableFlag
```

Any ideas on how to suppress the duplication for now or fix the parser?

**Comment by bobsta63** [comment]
Hi Kev!

That's strange - My installation does not show duplicated test results -
Just wondering do you get the same results when you attempt to run the unit
tests locally? (using phpunit)

**Comment by Caffe1neAdd1ct** [comment]
Hey Bobby, 

Just removed the tap logging line out of phpunit.xml as the phpci seems to be executing the phpunit command with this flag already set, now getting a slightly better output (still erroring though):

```
ok 66 - Services_Model_VpsTest::testIsDomainAvailable
ok 67 - Services_Model_VpsTest::testIsAvailable
ok 68 - User_Form_UserRegisterTest::testInit
1..68
[1;37;40mCode Coverage Report:        
[1;37;40m  2015-01-20 12:12:10        
[1;37;40m                             
[1;37;40m Summary:                    
[37;41m  Classes:  3.96% (4/101)    
[37;41m  Methods:  3.63% (56/1544)  
[37;41m  Lines:    1.68% (175/10403)
@Billing.Model::Billing_Model_Country
  [30;42mMethods: 100.00% (18/18)   [30;42mLines: 100.00% ( 26/ 26)
@Billing.Model::Billing_Model_VatApi
  [30;42mMethods: 100.00% (13/13)   [30;42mLines: 100.00% ( 19/ 19)
@Billing.Model::Billing_Model_VatService
  [30;42mMethods: 100.00% (12/12)   [30;42mLines: 100.00% ( 63/ 63)
@Node.Model::Node_Model_NodeService
  [30;43mMethods:  75.00% ( 6/ 8)   [30;43mLines:  89.29% ( 50/ 56)
@Services.Model::Services_Model_Vps
  [30;42mMethods: 100.00% ( 7/ 7)   [30;42mLines: 100.00% ( 17/ 17)
Exception: Invalid TAP string, number of tests does not match specified test count.
PLUGIN: FAILED
BUILD FAILED
Removing Build.
```

Tests are all passing locally with netbeans pointed at the vendor/bin/phpunit inside the project.

**Comment by bobsta63** [comment]
Sorry bud, not sure then mate :( - I'm sure someone else around here may know though ;)

**Comment by Caffe1neAdd1ct** [comment]
Looks like i've got the same issue as reported by @tobiastom :

```
ok 68 - User_Form_UserRegisterTest::testInit
1..68
```

The Tap parser is falling over at `1..68`.

@wandersonwhcr any luck pulling in #674 ?

**Comment by Caffe1neAdd1ct** [comment]
Ah removing the following section now has phpunit running:
```
<logging>
        <log type="coverage-text" target="php://stdout" showUncoveredFiles="false"/>
    </logging>
```

Looks like the docs need some love: https://www.phptesting.org/wiki/PHP-Unit-Plugin

**Comment by flowl** [comment]
@Caffe1neAdd1ct do you use XML configuration?
I encountered the same issue (#674), the docs say "If you are using xml configuration, make sure you include logging output" (the snippet you showed) - but I am using XML configuration (do you?) and it's not working.

Correct me if I'm wrong, but it should be "If you are using xml configuration, make sure you DO NOT include logging output".

**Comment by Caffe1neAdd1ct** [comment]
@flowl I think you are right, I removed the logging output section from my phpunit.xml and it started working (after tweaking the path setting in phpci.yml as well).

Looking at the docs that snippet was needed when the phpunit was a plugin and not part of the core? Seems to have changed how the results are collected...

**Comment by wandersonwhcr** [comment]
@Caffe1neAdd1ct as mentioned before, we have two options: fix it or refactor `TapClass`. Any suggestions?

**Comment by Caffe1neAdd1ct** [comment]
@wandersonwhcr I like the idea of refactoring to use the JSON output, however might be worth fixing the current implementation quickly then looking at the larger refactor task.

Also i've noticed code coverage isn't displayed anywhere which would also be very nice, think there is an xml clover based logger output which could be read and displayed... Netbeans gives a very nice overview of the code coverage from the clover style xml report.

Extra option added to netbeans phpunit ran command: ```--coverage-clover" "/tmp/nb-phpunit-coverage.xml```

I'm always a little tight on time however if some spare hours come up i'd like to contribute and help out :+1:

**Comment by wandersonwhcr** [comment]
@Caffe1neAdd1ct I like it too. However, IMHO we must have a :+1: from collaborators. @Adirelle can you help us?

**Comment by Caffe1neAdd1ct** [comment]
Helpful link: https://phpunit.de/manual/current/en/logging.html

Worth a read though for the possible outputs from phpunit...

**Comment by Adirelle** [comment]
@wandersonwhcr I'm no collaborator. Anyway, I agree the TapParser and PHPUnit plugin need some love to be more robust.

**Comment by wandersonwhcr** [comment]
@Adirelle oh, I'm sorry :)

**Comment by tomschlick** [comment]
I'm seeing this with codeception... Any suggestions?

```sh

RUNNING PLUGIN: codeception
TAP version 13
ok 1 - try to access the dashboard as a guest (Auth/GuestAccessDashboardAndRedirectCept)
ok 2 - see the login page (Auth/SeeLoginCept)
ok 3 - click forgot password and see the email form (Auth/SeeLoginForgotPasswordCept)
ok 4 - see powered by runmybusiness branding (Auth/ShouldSeePoweredByBrandingCept)
ok 5 - submit invalid credentials (Auth/SubmitLoginAndFailCept)
ok 6 - submit valid credentials and see the dashboard (Auth/SubmitLoginAndSucceedCept)
1..6

Exception: Invalid TAP string, number of tests does not match specified test count.
PLUGIN: FAILED

```

I'm running PHPCI 1.6 (released today)

**Comment by steve-todorov** [comment]
Hey everybody, 

I'm having the exact same issue with the PHPUnit test cases. The tests work fine locally, but with PHPCI it returns the `Exception: Invalid TAP string, number of tests does not match specified test count.` exception and runs them at least 2 times. As I see, this issue has been around for quite some time now. Is anybody working on it?

**Comment by Adirelle** [comment]
@steve-todorov Could you please to test #847 locally to see if it fixes the issue ? It cannot properly show the test results yet but at least it should fail the build.

**Comment by CatoTH** [comment]
I ran into the same error message using codeception. #847 seems to work as described - the build process doesn't crash anymore. The test results mostly consist of "undefined::undefined"-Strings, though.

**Comment by Adirelle** [comment]
This is mainly a matter of display; the data should be ok in the database. I will try to fix it.

**Comment by steve-todorov** [comment]
@Adirelle  I'm sorry for my late response, but I was busy last week and only now had the time to tryout your fix. It doesn't seem to be working right for me. I'm using the latest version of PHPUnit which currently is 4.6 (installed with composer globally and is available via phpunit in the $PATH) and latest php 5.6.7. Unfortunately the project is failing. You can find my build log [here](https://gist.github.com/steve-todorov/ea10bf93f47167dd7d96). I created a simple Symfony project which you could use for testing https://bitbucket.org/steve-todorov/testing-symfony-phpci. The tests are passing either via terminal and PHPUnit or in PHPStorm but failing in PHPCI.

**Comment by Adirelle** [comment]
@steve-todorov I see. This is a "double tap output" bug ; it is not related to the TapParser but your PHPUnit configuration. Try removing tap output from the phunit.xml, see: https://github.com/Block8/PHPCI/issues/571#issuecomment-70651591.

**Comment by steve-todorov** [comment]
Ahh, you're absolutely right. It seems to be working fine now. Unfortunately this configuration would output only this upon test fails:

```
RUNNING PLUGIN: php_unit
PLUGIN: FAILED
BUILD FAILED
Removing Build.
```

As you can imagine, when having multiple test cases it might take forever to figure out why or what's failing. Furthermore, the build directory is removed right after the build and even if there are any logs there you won't be able to go though them. Is there an other option to set in phpci so that I could see the phpunit output in the build log?

**Comment by Adirelle** [comment]
I've updated my PR to fix the display of test results. Could you check it please ?

**Comment by pixelpeter** [comment]
The problem still exists for me with phpci 1.6.0 and codeception 2.0.14 using this project https://github.com/janhenkgerritsen/codeception-laravel5-sample for trying out phpci
```
[2015-06-19 21:58:21] RunCommand.ERROR: Exception: Invalid TAP string, number of tests does not match specified test count. {"exception":"[object] (Exception(code: 0): Invalid TAP string, number of tests does not match specified test count. at /var/www/phpci.dev/PHPCI/Plugin/Util/TapParser.php:76)","buildID":"22"} []
```

**Comment by martinberlin** [comment]
Please check here for a new version of the TAP parser:
https://raw.githubusercontent.com/Block8/PHPCI/master/PHPCI/Plugin/Util/TapParser.ph

And replace it in the directory:
phpci/PHPCI/Plugin/Util

I've tried this and it worked out for me.
